### PR TITLE
Add some more blog entries

### PR DESCRIPTION
**Pull request by juliakreger**
And pixie boots as an author on behalf of the project.
Since he is our mascott.

### CODE REVIEW

**Comment by juliakreger** [comment]
Halp! What am I doing wrong?!

**Comment by jimmytipit** [comment]
It looks like your packagelock.json might be corrupted.  Try the following:

$ rm -rf package-lock.json node_modules <-- you need both
$ npm install

And then re-commit.  Also, can try to run the code locally using the instructions in the read.me to see if it will build.

**Comment by juliakreger** [comment]
> It looks like your packagelock.json might be corrupted. Try the following:
> 
> $ rm -rf package-lock.json node_modules <-- you need both
> $ npm install
> 
> And then re-commit. Also, can try to run the code locally using the instructions in the read.me to see if it will build.

So, slightly different path but it works until i try and copy one of the blog post files into view so it is rendered. Plus I don't have a packagelock.json, and I've wiped out the modules and reinstalled.

# rm -r -f node_modules && yarnpkg install && yarnpgk build

As mentioned, above, it works without the blog files being present.  :\  I've tried completely reformatting, rewriting,etc. I feel like it is some sort of fundamental formatting issue. :\

**Comment by jimmytipit** [comment]
I'm going to copy your code locally and see if I can figure it out :) Will try to have something up and fixed in the next few hours.

Cheeres,
Jimmy

**Comment by juliakreger** [comment]
If you figure it out, just let me know. I'm still poking/prodding
formatting. It just makes no sense. I think it is when it is trying to make
a summary except string, but non-familiarity with the toolset doesn't help.

**Review by jimmytipit — COMMENTED** [review]
@juliakreger I think I see the issue.  The markdown for the links is slightly off:

Second part w/ the link should be parentheses i/o brackets.  That's in multiple files.

Ironic contributor Arne Wiebalck writes in a recent blog update on the [CERN TechBlog](https://techblog.web.cern.ch/techblog/post/why-ironic/) about why they use Ironic and how it helps them support their users and ultimately their mission.

**Comment by jimmytipit** [comment]
Hooray! It worked: https://609017cd1fadf10007b22b10--ironicbaremetal.netlify.app/blog/

**Pull request merged**
